# deep space probe trajectory

with radio equipment of deep space probe,we get stream of vector data showing how probe position comapres with desired trajectory.if at kth data we assuem X = [x1 x2 .... xk]

we calculate gram matrix as X^t x = GK,its not efficent to compute it each time,isnetad,at time k+1 we can partion X as X = [Xk xk+1] then the gram matrix is Gk+1 = Gk + X(k+1)

^T x(k+1)

In [1]:
#importing numpy

import numpy as np

In [2]:
#initial gram matrix

X = np.array([
    [2 , 4] ,

    [5  , 8]
])

X_transpose = X.T

Gram = X_transpose @ X

print(Gram)

[[29 48]
 [48 80]]


In [3]:
#for new data 
x_new  = np.array([3, 7])

new_Gram = Gram + ( (x_new.T) @ x_new)

print(new_Gram)

[[ 87 106]
 [106 138]]


In [4]:
#Check

X = np.array([
    [2 , 4] , 

    [5 , 8] , 

    [3 , 7]
])

X_transpose = X.T

new_gram = X_transpose @ X

print(new_Gram)

[[ 87 106]
 [106 138]]
