# Intrapolating_polynomial

An intrapolating polynomial is a polynomial wich pathes through all data points,used for finding points between them.we have six data points:

(velocity , force) -> (0,0) , (2,2.9) , (4 , 14.8) , (6 , 39.6 ) , (8 , 74.3) , (10 , 119)

We use system of linear equations method to solve this.

To avoid  overdetermined or underdetermined system , we use polynomial of degree 5.

we use velocities as coefficents and find parameters based on it

In [2]:
#Importing numpy

import numpy as np

#Importing solve function
from numpy.linalg import solve

In [12]:
#Froming coefficent matrix
constant_column = [1 , 1 , 1 , 1 , 1 , 1]

data_row =  np.array([0 , 2 , 4 , 6 , 8 , 10])

coefficent_matrix = np.array([ 0 , 2 , 4 , 6 , 8 , 10])

coefficent_matrix = np.vstack((constant_column, coefficent_matrix))

coefficent_matrix = np.vstack((coefficent_matrix , data_row ** 2))

coefficent_matrix = np.vstack((coefficent_matrix , data_row ** 3))

coefficent_matrix = np.vstack((coefficent_matrix , data_row ** 4))

coefficent_matrix = np.vstack((coefficent_matrix , data_row ** 5))

coefficent_matrix = coefficent_matrix.T

print(coefficent_matrix)


[[     1      0      0      0      0      0]
 [     1      2      4      8     16     32]
 [     1      4     16     64    256   1024]
 [     1      6     36    216   1296   7776]
 [     1      8     64    512   4096  32768]
 [     1     10    100   1000  10000 100000]]


In [14]:
#Forming augmented column
augmented_column = np.array([0 , 2.9 , 14.8 , 39.6 , 74.3 , 119])

print(augmented_column)

[  0.    2.9  14.8  39.6  74.3 119. ]


In [17]:
#SOlving intrapolating polynomial

solution = solve(coefficent_matrix , augmented_column)

polynomial = f"{solution[0]} * a0"

for i in range(1 , solution.size):

    polynomial += f" + {solution[i]} * a{i}"

print(polynomial)

0.0 * a0 + 1.712499999999953 * a1 + -1.194791666666623 * a2 + 0.6614583333333219 * a3 + -0.07005208333333213 * a4 + 0.002604166666666622 * a5
