# RREF FORM

in this script we solve a linear system of equations using reduced row echelon form of it's agumented matrix,by using pivots,we make each entry below pivot zero,transforming it

to echelon form,then turning each pivot to 1 by scaling and removing all entries above them,we can find uniqness or consitency of a system of equations too.geometriclly it's 

intersection of hyperplanes.each step involves in a fundemental row operation :

1.adding a multiply of a row to another

2.scaling a row by a non zero constant

3.interchanging two rows

In [2]:
#Importing numpy

import numpy as np

In [31]:
"""
This example agumented matrix is for this system of linear equations:

x1 - 2 * x2 + x3 = 0

2 * x2 - 8 * x3 = 8

5 * x1 - 5 * x3 = 10
"""

#Coefficent matrix
coefficient_matrix = np.array([

    [1,-2,1] ,

    [0 , 2 , -8] ,

    [5,0,-5] ,
] , dtype=np.float64)


#Solution_vector
intercept_vector = np.array([0,8,10] , dtype=np.float64)

#Agumented matrix
augmented_matrix = np.concatenate((coefficient_matrix, intercept_vector[:,np.newaxis]), axis = 1)

print(augmented_matrix)

[[ 1. -2.  1.  0.]
 [ 0.  2. -8.  8.]
 [ 5.  0. -5. 10.]]


In [32]:
"""
Each step of rref is as follows:

1.row_3 - 5 row_1

2.0.5 * row_2

3. 0.1 * row_3

4.row_3 - row_2

5.(1/3) * row_3

6.row_2 + 4 * row_3

7.row_1 - row_3

8.row_1 + 2 * row_2
"""

#Step_1
augmented_matrix[2] -= 5 * augmented_matrix[0]

print(augmented_matrix)

#Step_2
augmented_matrix[1] *= (0.5)

print(augmented_matrix)

#Step_3
augmented_matrix[2] *= 0.1

print(augmented_matrix)

#Step_4
augmented_matrix[2] -= augmented_matrix[1]

print(augmented_matrix)

#Step_5
augmented_matrix[2] *= (1 / 3)

print(augmented_matrix)

#Step_6
augmented_matrix[1] += 4 *  augmented_matrix[2]

print(augmented_matrix)

#Step_7
augmented_matrix[0] -= augmented_matrix[2]

print(augmented_matrix)

#Step_8
augmented_matrix[0] += 2 * augmented_matrix[1]

print(augmented_matrix)




[[  1.  -2.   1.   0.]
 [  0.   2.  -8.   8.]
 [  0.  10. -10.  10.]]
[[  1.  -2.   1.   0.]
 [  0.   1.  -4.   4.]
 [  0.  10. -10.  10.]]
[[ 1. -2.  1.  0.]
 [ 0.  1. -4.  4.]
 [ 0.  1. -1.  1.]]
[[ 1. -2.  1.  0.]
 [ 0.  1. -4.  4.]
 [ 0.  0.  3. -3.]]
[[ 1. -2.  1.  0.]
 [ 0.  1. -4.  4.]
 [ 0.  0.  1. -1.]]
[[ 1. -2.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1. -1.]]
[[ 1. -2.  0.  1.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1. -1.]]
[[ 1.  0.  0.  1.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1. -1.]]


In [33]:
#Solution_vector

solution_vector = np.array([x for x in augmented_matrix[:,3]])

print(solution_vector)

[ 1.  0. -1.]
