# RRef_analysis

In this script we use reduced row echelon form to analyze consitency and uniqness of solutions of system of linear equations.and solve them if it's consitence.

In [2]:
#Importing numpy

import numpy as np

In [3]:
def rref(matrix : np.array) -> np.array :

    """This function row reduces the example matrix,not a general function"""
   
    temp = matrix[0].copy()

    matrix[0] = matrix[3].copy()

    matrix[3] = temp.copy()

    matrix[1] += matrix[0]

    matrix[2] += ( 2 * matrix[0])

    matrix[1] *= (0.5)

    matrix[2] *= (0.2)

    matrix[2] -= matrix[1]

    matrix[3] += (3 * matrix[1])

    temp = matrix[2].copy()

    matrix[2] = matrix[3].copy()

    matrix[3] = temp.copy()

    matrix[2] *= (-0.2)

    matrix[1] += ( 3 * matrix[2])

    matrix[0] += (9 * matrix[2])
    
    matrix[0] -= ( 4 * matrix[1])
    
    print(matrix)

    print()


In [4]:
def consistency(matrix : np.array) -> bool :

    """This function checks if a system of linear equations is consitence"""

    size = matrix.shape

    no_leading_entry = True

    consistence = True

    i = 0

    while i < size[0] and  consistence:

        for j in range(size[1] - 1):

            if matrix[i , j] != 0:

                no_leading_entry = False

                break

        if no_leading_entry and matrix[i , size[1] - 1] != 0:

            consistence = False

            break

        no_leading_entry = True

        i += 1

    return consistence

In [5]:
def uniqness(matrix : np.array) -> bool:

    """This function checks if a system of linear equations has one solution or infintily many"""
    
    size = matrix.shape
    
    unique = True

    if size[1] - 1 > size[0]:

        unique = False

    else:

        for i in range(size[0]):

            if matrix[i , i] == 0:

                uniqne = False

                break

    return unique

In [30]:
def solutions(matrix : np.array):

    """This function prints out parametric description of system of linear equations"""

    size = matrix.shape
    
    row_of_all_zeroes = True
    
    solution = ""

    leading_entry = True

    parametric_description = ["0"]  * size[1]

    pivot_position = 0

    for i in range(size[0]):

        for j in range(size[1]  - 1):

            if matrix[i , j] == 1 and leading_entry:

                pivot_position = j

                row_of_all_zeroes = False

                leading_entry = False

                solution = f"x{j + 1} = {matrix[i , size[1] - 1]}"

                parametric_description[j] = solution

            elif matrix[i , j] != 0 and not leading_entry:

                solution += f" + {-1 * matrix[i , j]} x{j + 1}"

                parametric_description[j] = f"x{j + 1} free"
        
        if row_of_all_zeroes:

            break

        else:
            
            parametric_description[pivot_position] = solution
            
            row_of_all_zeroes = True

            leading_entry = True

            solution = ""

    for i in parametric_description:
        
        if i != "0":

            print(i)

            print()

In [31]:
matrix = np.array([

        [0 , -3 , -6 , 4 , 9] , 

        [-1 , -2 , -1, 3 , 1] , 

        [-2 , -3 , 0 , 3 , -1] , 

        [1 , 4 , 5 , -9 , -7]
    ] , dtype= np.float64)
    
rref(matrix)

print(f"consistence? {"Yes" if consistency(matrix) else "No"}")

print()

print(f"unique solutions? {"Yes" if uniqness(matrix) else "NO"}")

print()

print("parametric description: ")

print()

print(solutions(matrix))

[[ 1.  0. -3.  0.  5.]
 [ 0.  1.  2.  0. -3.]
 [-0. -0. -0.  1. -0.]
 [ 0.  0.  0.  0.  0.]]

consistence? Yes

unique solutions? Yes

parametric description: 

x1 = 5.0 + 3.0 x3

x2 = -3.0 + -2.0 x3

x3 free

x4 = -0.0

None
