# shur complement

in this script we implement how to calculate shur compelemnt with an example statistical application 

assume we have a data matrix X and then we add new predictor x0 to form W = [X x0] partitioning

In [1]:
#importing numpy


import numpy as np

In [2]:
#constructing w

n = 3

m = 10

np.random.seed(0)

X  = np.random.randn(m , n)

x0 = np.random.randn(m , 1)

W = np.hstack([X  , x0])

print(W)

[[ 1.76405235  0.40015721  0.97873798  0.15494743]
 [ 2.2408932   1.86755799 -0.97727788  0.37816252]
 [ 0.95008842 -0.15135721 -0.10321885 -0.88778575]
 [ 0.4105985   0.14404357  1.45427351 -1.98079647]
 [ 0.76103773  0.12167502  0.44386323 -0.34791215]
 [ 0.33367433  1.49407907 -0.20515826  0.15634897]
 [ 0.3130677  -0.85409574 -2.55298982  1.23029068]
 [ 0.6536186   0.8644362  -0.74216502  1.20237985]
 [ 2.26975462 -1.45436567  0.04575852 -0.38732682]
 [-0.18718385  1.53277921  1.46935877 -0.30230275]]


In [3]:
#Computing W^t w with paritoning [X x0]

A11 = X.T @ X

A12 = X.T @ x0

A21 = x0.T @ X

A22 = x0.T @ x0

In [4]:
#shur complement

A11_inverse = np.linalg.inv(A11)

S = A22 - A21 @ A11_inverse @ A12

print(S)

[[3.28516971]]


In [5]:
#veirfy using projection matrix M

M = np.eye(m) - (X @ A11_inverse @ X.T)

s_check = x0.T @ M @ x0

print(s_check)

[[3.28516971]]


In [9]:
#relation to W^t w ( 1 / s is porportional to variance )

WtW_inverse = np.linalg.inv(W.T @ W)

print(WtW_inverse[-1 , -1])

print(f"using S = {1 / S}")

0.3043982772970276
using S = [[0.30439828]]
